# Default configuration; no IDs nor a token have been set.

datafiles:
    author_list:        "files/about/authors.md"
    keyfile:            "files/AnonMessages/key.bin"
    slurfile:           "files/SlurAlerts/slurs.txt"
    goodwordfile:       "files/SlurAlerts/goodword.txt"
    blacklist:          "files/WBList/blacklist.csv"
    casedetails:        "files/Cases/casedetails.pkl"
    casehistory:        "files/Cases/casehistory.pkl"
    gifblacklist:       "files/WBList/gifblacklist.txt"
    secret_dms:         "files/AnonMessages/secret_dms.pkl"
    secret_mutes:       "files/AnonMessages/banned.csv"
    reform_iter:        "files/Reformation/reformationiter.txt"
    reformation_cases:  "files/Reformation/reformationcases.pkl"
    watchlist:          "files/WBList/watchlist.csv"
    ticketers:          "files/Tickets/ticketers.pkl"
    video_history:      "files/youtube/processed_videos.txt"
    alert_logs:         "files/Alerts/alerts.pkl"
    alert_csv:          "files/Alerts/alerts.csv"
    sersi_db:           "persistent_data/sersi.db"

bot:
    prefix: "s!"
    status: "melanie did this"
    port:   8113 # 8074 for live, 8113 for unstable
    minimum caps length: 8
    version: "4.0.0"
    git_url: "https://github.com/Yoshod/Sersi"
    authors:
        - "• Hekkland#0001 `261870562798731266`"
        - "• kisachi#7272  `348142492245426176`"
        - "• Gombik#0935   `264502855602274306`"

channels:
    alert:             977377171054166037
    logging:           977925156330672198
    false positives:   978079399066882059
    mod_logs:          978346814904336484
    reformation:       984879845727150100
    reformation_info: 1004289125509238915
    dm_forward:        982057670594928660
    errors:            987397664280817754
    secret:            982057670594928660
    teachers_lounge:   988931699268280350
    reform public log: 988937445481512980
    ban appeals:       991390873239683202
    photography:       0
    youtube:           0
    tamper_logs:      1021128961515847730
    logging_category: 1006622093347127499
    admin_ticket_logs: 1021380970240294922
    senior_ticket_logs: 1021380970240294922
    mod_ticket_logs: 1021380970240294922
    verification_ticket_logs: 1021380970240294922
    deleted_messages: 0
    mod applications: 977377171054166037
    cet applications: 0
    internalfeedback: 0
    timeoutappeals: 0
    video_discussion: 0
    role_logs:                                 0
    ageverification: 977377171054166037


roles:
    reformation:                978334782968721468
    reformed:                   878289678623703080
    probation:                  984195306038124558
    never_mod:                  878045315784114216
    civil_engineering_initiate: 878040658244403253
    newbie:                     938465528043954267
    honourable_member:          0
    adult_access:               1094367708306477126
    adult_verified:             1094367738107019324

opt_in_roles:
    gaming:         0
    tech_compsci:   0
    food_and_drink: 0
    education:      0
    art:            0
    anime:          0
    furry:          0
    models:         0
    shillposting:   0
    music:          0
    photography:    0
    environment:    0

permission_roles:
    staff:             978678150789754890
    reformist:         943193811574751314
    ticket_support:    1021477270331850795
    sersi_contributor: 978677753945657356
    trial_moderator:   1021476974901870652
    moderator:         977394150494326855
    senior_moderator:  1021477021664153653
    dark_moderator:    978681533453971526
    cet: 0
    cet_lead: 0

emotes:
    success: "<:sersisuccess:979066662856822844>"
    fail:    "<:sersifail:979070135799279698>"

invites:
    adam_something_ban_reinvite:        "https://discord.gg/F6vMRTbuFk"
    ban_appeal_server:                  "https://discord.gg/dGpvCbrBRA"

guilds:
    main: 977377117895536640
    errors: 977377117895536640

punishment roles:
    annoying:                 1023985995898683463
    terrible_ideas:           1023986985209167954
    politics_and_debate_mute: 986009181733654528
    probation:                984195306038124558
    ancap:                    1023986097002385408
    problem_child:            1023986949918314609