import os
import random
from datetime import datetime, timezone

import sqlalchemy
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Integer,
    BigInteger,
    String,
    PrimaryKeyConstraint,
)
from sqlalchemy.orm import scoped_session, sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base
from dotenv import load_dotenv

from utils.base import encode_snowflake


def random_id() -> str:
    """Generates a random, short, unique ID."""
    return encode_snowflake(random.getrandbits(64))


# --- Database Setup ---
# Load the DATABASE_URL from your .env file
load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable is not set.")

# A single engine and a single Base for the entire application
engine = sqlalchemy.create_engine(DATABASE_URL)
Base = declarative_base()

# A single sessionmaker for the entire application.
# Use `SessionLocal()` to get a new session.
SessionLocal = scoped_session(
    sessionmaker(autocommit=False, autoflush=False, bind=engine)
)


# --- Table Definitions ---


class Guilds(Base):
    """
    Represents the Guilds table in the database.

    Attributes:
        __tablename__ (str): The name of the table in the database.
        guild_id (int): The primary key of the guild.
        is_premium (bool): Indicates whether the guild has premium status. Defaults to False.
        was_premium (bool): Indicates whether the guild previously had premium status. Defaults to False.
        is_testing (bool): Indicates whether the guild is in testing mode. Defaults to False.
        is_banned (bool): Indicates whether the guild is banned. Defaults to False.
        finished_setup (bool): Indicates whether the guild has completed the setup process. Defaults to False.
        join_date (datetime): The date and time when the guild joined. Defaults to the current UTC time.
        leave_date (datetime): The date and time when the guild left.
    """

    __tablename__ = "guilds"
    guild_id = Column(BigInteger, primary_key=True)
    is_premium = Column(Boolean, default=False)
    was_premium = Column(Boolean, default=False)
    is_testing = Column(Boolean, default=False)
    is_banned = Column(Boolean, default=False)
    finished_setup = Column(Boolean, default=False)
    join_date = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    leave_date = Column(DateTime)


class Modules(Base):
    """
    Represents a database model for modules associated with a guild.

    Attributes:
        __tablename__ (str): The name of the database table, "modules".
        guild_id (int): The ID of the guild this module is associated with.
            This is a foreign key referencing the "guilds.guild_id" column.
        module_name (str): The name of the module.
        enabled (bool): Indicates whether the module is enabled. Defaults to False.
        __table_args__ (tuple): Specifies a composite primary key constraint
            on the "guild_id" and "module_name" columns.
    """

    __tablename__ = "modules"
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), index=True)
    module_name = Column(String)
    enabled = Column(Boolean, default=False)
    __table_args__ = (PrimaryKeyConstraint("guild_id", "module_name"),)


class Language(Base):
    """
    Represents the language settings for a guild.

    Attributes:
        __tablename__ (str): The name of the database table, "language".
        guild_id (int): The ID of the guild, serving as a foreign key to the "guilds" table and a primary key for this table.
        language (str): The language preference for the guild, defaulting to "en".
    """

    __tablename__ = "language"
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), primary_key=True)
    language = Column(String, default="en")


class Case(Base):
    """
    Case Table

    The `Case` table serves as the central table for all moderation cases. It contains
    information about various types of moderation actions and their associated metadata.

    Attributes:
        __tablename__ (str): The name of the table in the database (`cases`).
        case_id (Column): A unique identifier for the case, generated by `random_id`.
        guild_id (Column): The ID of the guild (server) where the case occurred.
                           This is a foreign key referencing the `guilds` table.
        case_type (Column): The type of moderation case (e.g., warning, ban, kick).
        offence (Column): A description of the offence or reason for the case.
        jump_url (Column): A URL to jump to the context of the case (e.g., a message link).
        state (Column): The current state of the case (e.g., open, closed).
        created_at (Column): The timestamp when the case was created. Defaults to the current UTC time.
        modified_at (Column): The timestamp when the case was last modified. Defaults to the current UTC time.

    Relationships:
        warning (relationship): A one-to-one relationship with the `WarningCase` table.
        timeout (relationship): A one-to-one relationship with the `TimeoutCase` table.
        ban (relationship): A one-to-one relationship with the `BanCase` table.
        reformation (relationship): A one-to-one relationship with the `ReformationCase` table.
        blacklist (relationship): A one-to-one relationship with the `BlacklistCase` table.
        kick (relationship): A one-to-one relationship with the `KickCase` table.
        raid (relationship): A one-to-one relationship with the `RaidCase` table.
        audit_logs (relationship): A one-to-many relationship with the `CaseAudit` table.
        moderators (relationship): A one-to-many relationship with the `CaseModerators` table.
        reviews (relationship): A one-to-many relationship with the `CaseReviews` table.
        groups (relationship): A one-to-many relationship with the `CaseGroups` table.
        raiders (relationship): A one-to-many relationship with the `Raiders` table.

    Primary Key:
        The combination of `case_id` and `guild_id` serves as the primary key for the table.

    Methods:
        __repr__: Returns a string representation of the case, including its type and offence.
    """

    __tablename__ = "cases"
    case_id = Column(String, default=random_id)
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), index=True)
    case_type = Column(String, nullable=False)
    offence = Column(String, nullable=False)
    jump_url = Column(String, nullable=False)
    state = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    modified_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (PrimaryKeyConstraint("case_id", "guild_id"),)

    # Relationships to child tables
    warning = relationship(
        "WarningCase",
        back_populates="case",
        uselist=False,
        cascade="all, delete-orphan",
    )
    timeout = relationship(
        "TimeoutCase",
        back_populates="case",
        uselist=False,
        cascade="all, delete-orphan",
    )
    ban = relationship(
        "BanCase", back_populates="case", uselist=False, cascade="all, delete-orphan"
    )
    reformation = relationship(
        "ReformationCase",
        back_populates="case",
        uselist=False,
        cascade="all, delete-orphan",
    )
    blacklist = relationship(
        "BlacklistCase",
        back_populates="case",
        uselist=False,
        cascade="all, delete-orphan",
    )
    kick = relationship(
        "KickCase", back_populates="case", uselist=False, cascade="all, delete-orphan"
    )
    raid = relationship(
        "RaidCase", back_populates="case", uselist=False, cascade="all, delete-orphan"
    )

    audit_logs = relationship(
        "CaseAudit", back_populates="case", cascade="all, delete-orphan"
    )
    moderators = relationship(
        "CaseModerators", back_populates="case", cascade="all, delete-orphan"
    )
    reviews = relationship(
        "CaseReviews", back_populates="case", cascade="all, delete-orphan"
    )
    groups = relationship(
        "CaseGroups", back_populates="case", cascade="all, delete-orphan"
    )
    raiders = relationship(
        "Raiders", back_populates="case", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"*{self.case_type}* `{self.offence or 'N/A'}`"


# --- Case Sub-Type and Related Tables ---


class CaseAudit(Base):
    """
    Represents an audit log entry for a case in the database.

    Attributes:
        id (str): The unique identifier for the audit log entry. Defaults to a randomly generated ID.
        case_id (str): The ID of the associated case.
        guild_id (int): The ID of the guild (server) associated with the case.
        field (str): The name of the field that was changed. Cannot be null.
        old_value (str): The previous value of the field before the change.
        new_value (str): The new value of the field after the change.
        author (int): The ID of the user who made the change.
        timestamp (datetime): The timestamp when the change was made. Defaults to the current UTC time.

    Relationships:
        case (Case): The associated case object. This relationship is back-populated by the `audit_logs` attribute in the `Case` model.

    Table Constraints:
        __tablename__ (str): The name of the database table, "cases_audit".
        __table_args__ (tuple): A foreign key constraint linking `case_id` and `guild_id` to the `cases` table, with cascading delete behavior.
    """

    __tablename__ = "cases_audit"
    id = Column(String, primary_key=True, default=random_id)
    case_id = Column(String)
    guild_id = Column(BigInteger)
    field = Column(String, nullable=False)
    old_value = Column(String)
    new_value = Column(String)
    author = Column(BigInteger)
    timestamp = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="audit_logs")


class WarningCase(Base):
    """
    Represents a warning case in the database.

    Attributes:
        case_id (str): The unique identifier for the warning case.
        guild_id (int): The identifier of the guild associated with the warning case.
        justification (str): The reason or justification for the warning. This field is required.

    Relationships:
        case (Case): A relationship to the `Case` model, representing the associated case.
                     This relationship is back-populated by the `warning` attribute in the `Case` model.

    Table Constraints:
        - PrimaryKeyConstraint: Composite primary key consisting of `case_id` and `guild_id`.
        - ForeignKeyConstraint: Composite foreign key linking `case_id` and `guild_id` to the `cases` table.
          Deletes associated warning cases when the referenced case is deleted (CASCADE).
    """

    __tablename__ = "warning_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="warning")


class TimeoutCase(Base):
    """
    Represents a timeout case in the database.

    Attributes:
        case_id (str): The unique identifier for the case.
        guild_id (int): The identifier for the guild associated with the case.
        justification (str): The reason or justification for the timeout. This field is required.
        scheduled_end (datetime): The scheduled end time for the timeout. This field is required.
        actual_end (datetime, optional): The actual end time for the timeout, if it has ended.

    Relationships:
        case (Case): A relationship to the `Case` model, representing the associated case.

    Table Constraints:
        - PrimaryKeyConstraint: Composite primary key consisting of `case_id` and `guild_id`.
        - ForeignKeyConstraint: Composite foreign key referencing `cases.case_id` and `cases.guild_id`
          with cascading delete behavior.
    """

    __tablename__ = "timeout_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)
    scheduled_end = Column(DateTime, nullable=False)
    actual_end = Column(DateTime)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="timeout")


class BanCase(Base):
    """
    Represents a ban case in the database.

    Attributes:
        case_id (str): The unique identifier for the ban case.
        guild_id (int): The ID of the guild where the ban case occurred.
        justification (str): The reason or justification for the ban. This field is required.
        ban_type (str): The type of ban applied. This field is required.

    Relationships:
        case (Case): A relationship to the `Case` model, representing the associated case.

    Table Constraints:
        - PrimaryKeyConstraint: Combines `case_id` and `guild_id` as the primary key.
        - ForeignKeyConstraint: Links `case_id` and `guild_id` to the `cases` table, with cascading delete behavior.
    """

    __tablename__ = "ban_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)
    ban_type = Column(String, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="ban")


class ReformationCase(Base):
    """
    ReformationCase is a SQLAlchemy model representing a table that stores information
    about reformation cases. Each reformation case is associated with a specific case
    and guild, and contains additional details such as justification and cell ID.

    Attributes:
        __tablename__ (str): The name of the database table ("reformation_cases").
        case_id (str): The unique identifier for the case.
        guild_id (int): The unique identifier for the guild associated with the case.
        justification (str): A mandatory field providing the justification for the reformation case.
        cell_id (int): A mandatory field representing the cell ID associated with the case.

    Relationships:
        case (Case): A relationship to the `Case` model, linking this reformation case
            to its parent case. This relationship is bidirectional and uses the
            `back_populates` attribute.

    Constraints:
        PrimaryKeyConstraint: A composite primary key consisting of `case_id` and `guild_id`.
        ForeignKeyConstraint: A foreign key constraint linking `case_id` and `guild_id`
            to the `cases` table, with cascading delete behavior.
    """

    __tablename__ = "reformation_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)
    cell_id = Column(BigInteger, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="reformation")


class BlacklistCase(Base):
    """
    Represents a blacklist case in the database.

    Attributes:
        __tablename__ (str): The name of the table in the database.
        case_id (str): The unique identifier for the blacklist case.
        guild_id (int): The ID of the guild associated with the blacklist case.
        justification (str): The reason or justification for the blacklist case. This field is required.
        blacklist_type (str): The type of blacklist. This field is required.

    Relationships:
        case (Case): A relationship to the `Case` model, representing the associated case.

    Table Constraints:
        - PrimaryKeyConstraint: Composite primary key consisting of `case_id` and `guild_id`.
        - ForeignKeyConstraint: Composite foreign key linking `case_id` and `guild_id` to the `cases` table, with cascading delete behavior.
    """

    __tablename__ = "blacklist_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)
    blacklist_type = Column(String, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="blacklist")


class KickCase(Base):
    """
    Represents a table of kick cases in a database.

    Attributes:
        __tablename__ (str): The name of the database table ("kick_cases").
        case_id (Column): A string column representing the unique identifier for the case.
        guild_id (Column): An integer column representing the unique identifier for the guild.
        justification (Column): A string column containing the justification for the kick. This field is required.

        __table_args__ (tuple):
            - PrimaryKeyConstraint: A composite primary key constraint on "case_id" and "guild_id".
            - ForeignKeyConstraint: A foreign key constraint linking "case_id" and "guild_id" to the "cases" table.
              Deletes cascade when the referenced case is deleted.

        case (relationship): A relationship to the "Case" model, with this model being the child in the relationship.
    """

    __tablename__ = "kick_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    justification = Column(String, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="kick")


class RaidCase(Base):
    """
    Represents a RaidCase entity in the database.

    Attributes:
        __tablename__ (str): The name of the database table, "raid_cases".
        case_id (str): The unique identifier for the raid case.
        guild_id (int): The identifier for the guild associated with the raid case.

    Relationships:
        case (Case): A relationship to the `Case` entity, with bidirectional
            back-population via the "raid" attribute.

    Table Constraints:
        - PrimaryKeyConstraint: Composite primary key consisting of "case_id" and "guild_id".
        - ForeignKeyConstraint: Composite foreign key referencing "cases.case_id" and
          "cases.guild_id", with cascading delete behavior.
    """

    __tablename__ = "raid_cases"
    case_id = Column(String)
    guild_id = Column(BigInteger)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="raid")


class CaseModerators(Base):
    """
    Represents the association between a case and its moderators in the database.

    Attributes:
        case_id (str): The unique identifier for the case.
        guild_id (int): The unique identifier for the guild (server) associated with the case.
        relation_to_case (str): The role or relationship of the moderator to the case.
        moderator_id (int): The unique identifier for the moderator.

    Table Constraints:
        - Primary Key: A composite key consisting of `case_id`, `guild_id`, `relation_to_case`, and `moderator_id`.
        - Foreign Key: Links `case_id` and `guild_id` to the `cases` table, with cascading delete behavior.

    Relationships:
        case: Establishes a relationship with the `Case` model, allowing access to the associated case and its moderators.
    """

    __tablename__ = "case_moderators"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    relation_to_case = Column(String)
    moderator_id = Column(BigInteger)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id", "relation_to_case", "moderator_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="moderators")


class CaseReviews(Base):
    """
    Represents a review of a case in the database.

    Attributes:
        __tablename__ (str): The name of the database table.
        case_id (str): The unique identifier for the case being reviewed.
        guild_id (int): The unique identifier for the guild associated with the case.
        reviewer_id (int): The unique identifier for the reviewer.
        outcome (bool): The outcome of the review (e.g., approved or rejected).
        timestamp (datetime): The timestamp of when the review was created, defaults to the current UTC time.
        __table_args__ (tuple): Additional table constraints, including:
            - A composite primary key on `case_id`, `guild_id`, and `reviewer_id`.
            - A foreign key constraint linking `case_id` and `guild_id` to the `cases` table, with cascading deletes.
        case (relationship): A relationship to the `Case` model, allowing access to the associated case and its reviews.
    """

    __tablename__ = "case_reviews"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    reviewer_id = Column(BigInteger)
    outcome = Column(Boolean, nullable=False)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id", "reviewer_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="reviews")


class CaseGroups(Base):
    """
    Represents a grouping of cases in the database.

    Attributes:
        __tablename__ (str): The name of the database table ("case_groups").
        case_id (str): The ID of the case, serves as part of the composite primary key.
        guild_id (int): The ID of the guild, serves as part of the composite primary key.
        group_id (int): The ID of the group, serves as part of the composite primary key. Defaults to a randomly generated ID.
        __table_args__ (tuple): Additional table arguments, including:
            - A composite primary key constraint on "case_id", "guild_id", and "group_id".
            - A foreign key constraint linking "case_id" and "guild_id" to the "cases" table, with cascading delete behavior.
        case (relationship): A relationship to the "Case" model, allowing access to the associated case and enabling back-population via the "groups" attribute in the "Case" model.
    """

    __tablename__ = "case_groups"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    group_id = Column(String, default=random_id)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id", "group_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="groups")


class Raiders(Base):
    """
    Represents a Raider entity in the database.

    Attributes:
        __tablename__ (str): The name of the database table, "raiders".
        case_id (Column): A string column representing the ID of the case.
        guild_id (Column): An integer column representing the ID of the guild.
        raider_id (Column): An integer column representing the ID of the raider.
        join_time (Column): A datetime column representing the time the raider joined. This field is required.

    Table Constraints:
        __table_args__:
            - PrimaryKeyConstraint: Ensures that the combination of "case_id", "guild_id", and "raider_id" is unique.
            - ForeignKeyConstraint: Links "case_id" and "guild_id" to the "cases" table, with cascading delete behavior.

    Relationships:
        case (relationship): Defines a relationship to the "Case" model, with back-population through the "raiders" attribute.
    """

    __tablename__ = "raiders"
    case_id = Column(String)
    guild_id = Column(BigInteger)
    raider_id = Column(BigInteger)
    join_time = Column(DateTime, nullable=False)

    __table_args__ = (
        PrimaryKeyConstraint("case_id", "guild_id", "raider_id"),
        ForeignKeyConstraint(
            ["case_id", "guild_id"],
            ["cases.case_id", "cases.guild_id"],
            ondelete="CASCADE",
        ),
    )
    case = relationship("Case", back_populates="raiders")


class Offences(Base):
    """
    Represents a database table for storing custom offences for each guild.

    Attributes:
        guild_id (int): The ID of the guild this offence is associated with.
                        It is a foreign key referencing the "guilds" table.
        offence_name (str): The name of the offence.
        offence_severity (int): The severity level of the offence. Defaults to 1.
        offence_description (str): A description of the offence.

    Table Constraints:
        PrimaryKeyConstraint: A composite primary key consisting of "guild_id"
                              and "offence_name".
    """

    """Stores custom offences for each guild."""

    __tablename__ = "offences"
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), index=True)
    offence_name = Column(String)
    offence_severity = Column(Integer, nullable=False, default=1)
    offence_description = Column(String)

    __table_args__ = (PrimaryKeyConstraint("guild_id", "offence_name"),)


class ModeratorRoles(Base):
    """
    ModeratorRoles is a database model that represents the roles of moderators in a guild
    and their associated permissions. Each record corresponds to a specific role within a
    guild and defines the actions that role is authorized to perform.

    Attributes:
        guild_id (int): The ID of the guild this role belongs to. Foreign key referencing the "guilds" table.
        role_id (int): The ID of the role within the guild.
        authority_level (int): The level of authority assigned to the role. Higher values indicate greater authority.
        can_warn (bool): Whether the role has permission to issue warnings. Defaults to False.
        can_timeout (bool): Whether the role has permission to timeout users. Defaults to False.
        can_immediate_ban (bool): Whether the role has permission to immediately ban users. Defaults to False.
        can_vote_ban (bool): Whether the role has permission to initiate or participate in vote-based bans. Defaults to False.
        can_unban (bool): Whether the role has permission to unban users. Defaults to False.
        can_reform (bool): Whether the role has permission to reform users. Defaults to False.
        can_blacklist (bool): Whether the role has permission to blacklist users. Defaults to False.
        can_kick (bool): Whether the role has permission to kick users. Defaults to False.
        declare_raid (bool): Whether the role has permission to declare a raid. Defaults to False.
        add_moderator (bool): Whether the role has permission to add new moderators. Defaults to False.
        remove_moderator (bool): Whether the role has permission to remove existing moderators. Defaults to False.
        is_immune (bool): Whether the role is immune to moderation actions. Defaults to False.
        edit_offences (bool): Whether the role has permission to edit offences. Defaults to False.
        edit_cases (bool): Whether the role has permission to edit cases. Defaults to False.

    Table Constraints:
        PrimaryKeyConstraint: A composite primary key consisting of "guild_id" and "role_id".
    """

    __tablename__ = "moderator_roles"
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), index=True)
    role_id = Column(BigInteger)
    authority_level = Column(Integer, nullable=False)
    can_warn = Column(Boolean, default=False)
    can_timeout = Column(Boolean, default=False)
    can_immediate_ban = Column(Boolean, default=False)
    can_vote_ban = Column(Boolean, default=False)
    can_unban = Column(Boolean, default=False)
    can_reform = Column(Boolean, default=False)
    can_blacklist = Column(Boolean, default=False)
    can_kick = Column(Boolean, default=False)
    declare_raid = Column(Boolean, default=False)
    add_moderator = Column(Boolean, default=False)
    remove_moderator = Column(Boolean, default=False)
    is_immune = Column(Boolean, default=False)
    edit_offences = Column(Boolean, default=False)
    edit_cases = Column(Boolean, default=False)

    __table_args__ = (PrimaryKeyConstraint("guild_id", "role_id"),)


class LoggingChannels(Base):
    """
    Represents a database table for logging channels in a guild.

    Attributes:
        __tablename__ (str): The name of the table in the database.
        guild_id (int): The ID of the guild, linked to the "guilds" table.
        log_type (str): The type of log (e.g., "moderation", "message_delete").
        channel_id (int): The ID of the channel where logs of the specified type are sent.

    Table Constraints:
        PrimaryKeyConstraint: A composite primary key consisting of "guild_id" and "log_type".
    """

    __tablename__ = "logging_channels"
    guild_id = Column(BigInteger, ForeignKey("guilds.guild_id"), index=True)
    log_type = Column(String, nullable=False)
    channel_id = Column(BigInteger, nullable=False)

    __table_args__ = (PrimaryKeyConstraint("guild_id", "log_type"),)


# --- Table Creation ---
def create_all_tables():
    """A function to create all the tables defined above."""
    Base.metadata.create_all(engine)


# This will ensure tables are created when the bot starts.
create_all_tables()
